### ISSUE TITLE
Capitalization on player URL

### ISSUE THREAD

**Issue by audas** [RamParameswaran/pyAFL#10]
PLayers/models.py when looking for the URL in the anchor tag if the player has multiple capitalization on the name it fails.

Setting the BeautifulSoup to ignore case fixed it. Notice the ,re.I

        **url_list = soup.findAll(
            "a",
            href=re.compile(f"players/{self.name[0]}/{self.name.replace(' ', '_')}",re.I),
        )**

**Comment by RamParameswaran** [comment]
Thanks @audas for raising this issue! Really good pickup! I didn't realise there were so many instances where the names have multiple capitalisation. FYI to other readers, one such example is "Duncan MacGregor".

Your solution is great.

Would you like to open a Pull Request for your patch? You have already written the solution in your comment, so it only seems fair! I'd be happy to help you with the process if you're new to contributing.

Cheers

**Comment by RamParameswaran** [comment]
Patched and merged in PR #11.
Closing.
