### ISSUE TITLE
Problem importing players as per read me in google Colab

### ISSUE THREAD

**Issue by esacht** [RamParameswaran/pyAFL#12]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-4f8cf96552e7> in <module>()
----> 1 from pyAFL.players.models import Player

/usr/local/lib/python3.7/dist-packages/pyAFL/players/models.py in <module>()
      4 
      5 from pyAFL import config
----> 6 from pyAFL.base.exceptions import LookupError
      7 
      8 # from pyAFL.base.models import AFLObject

ModuleNotFoundError: No module named 'pyAFL.base'

**Comment by DavidJArnold** [comment]
This is an issue with the PyPI packaging. I think it can be fixed by adding an __init__.py file to pyAFL/base. Without it, setuptools doesn't recognise base as a module and doesn't include it with the files packaged for PyPI.

**Comment by RamParameswaran** [comment]
Thanks for clarifying this @DavidJArnold. And thanks @esacht for raising it.

Indeed the `./base` directory was not included in the PyPI package because the directory was missing an `__init__.py`. This SO answer summarises the issue https://stackoverflow.com/a/56277323

**Comment by RamParameswaran** [comment]
This issue is fixed in release v0.2.1 :+1:
