### ISSUE TITLE
Adelaide Crows team being read in as Port Adelaide for season stats

### ISSUE THREAD

**Issue by cheese-egg** [RamParameswaran/pyAFL#23]
Thanks for this code, it's really useful for my project. However, when I attempt to read in Adelaide Crows season stats using this command

ADE.season_stats(2022)

I get stats for Port Adelaide players. Is this a known issue and is there a way to fix this?

Thank you

**Comment by RamParameswaran** [comment]
Hi @cheese-egg, yes it's a known issue - someone else started writing a fix, but didn't merge it into the master branch.

But this is a good reminder for me to have another look. I'll see if I can quickly fix it now.

**Comment by RamParameswaran** [comment]
Indeed I was able to quickly fix it :) 
I've merged the fix into the master branch of this repo, and I've released a new version to PIP (v0.4.2).

Please let me know if you have any further issues.
Closing this issue now. Thanks

**Comment by cheese-egg** [comment]
Thank you so much for the quick fix Ram.

I will check it later and let you know if there are any issues, but I'm
sure it will be fine.

Cheers
Dennis

**Comment by cheese-egg** [comment]
Hi Ram

I'm not sure if I've missed something here but I can't seem to pip install
the latest version you just created. I only seem to be able to get version
0.3.1. Do you have any idea why this might be?

[image: image.png]

Thanks again for your help!

Dennis

**Comment by RamParameswaran** [comment]
Hey Dennis. Hmm have you tried specifying the version number? See this link https://towardsdatascience.com/pip-install-specific-version-how-to-install-a-specific-python-package-version-with-pip-1f97e1002f31

If that doesn't work, it should at least give an error message why it failed. Let me know how it goes.

**Comment by cheese-egg** [comment]
Hi Ram

Thanks so much for your help in the past with your pyAFL package, it's
really a great package.

I was wondering if you will be updating it to include the games from 2024?
At the moment it seems to be the end of 2023.

[image: image.png]

Thanks again for your help!
Dennis

**Comment by cheese-egg** [comment]
Hi Ram

I was just following up on this email. Will you be updated the package to
include 2024 data. Thank you so much for the work you have done on this
package, it has been very helpful.

Regards
Dennis
